/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "auth": {
        "NotFound": string;
        "passwordsDoNotMatch": string;
        "phoneAlreadyInUse": string;
        "firstNameRequired": string;
        "lastNameRequired": string;
        "emailRequired": string;
        "fcmTokenRequired": string;
        "emailAlreadyInUse": string;
        "passwordMinLength": string;
        "phoneNumberRequired": string;
        "invalidPhoneNumber": string;
        "invalidEmail": string;
        "roleInvalid": string;
        "invalidLatitude": string;
        "invalidLongitude": string;
        "locationInvalid": string;
        "profilePictureInvalid": string;
        "platformRequired": string;
        "invalidPasswordFormat": string;
        "passwordRequired": string;
        "firstNameMinLength": string;
        "firstNameMaxLength": string;
        "lastNameMinLength": string;
        "lastNameMaxLength": string;
        "emailMaxLength": string;
        "invalidFirstName": string;
        "invalidLastName": string;
        "invalidFcmToken": string;
        "invalidPlatformType": string;
        "userNotFound": string;
        "passwordMismatch": string;
        "emailAlreadyExists": string;
        "invalidRole": string;
        "googleTokenMissingEmail": string;
        "invalidOtp": string;
        "otpVerificationRequired": string;
        "tokenNotFound": string;
        "fcmTokenRegistered": string;
        "loggedOut": string;
        "otpSent": string;
        "phoneVerified": string;
        "emailVerified": string;
        "passwordResetSuccess": string;
        "passwordConfirmed": string;
        "profileCompleted": string;
        "emailAlreadyVerified": string;
        "emailConfirmationTokenExpired": string;
        "badConfirmationToken": string;
        "phoneNumberNotFound": string;
        "noPhoneRecord": string;
        "otpCodeMissing": string;
        "otpCodeInvalid": string;
        "emailConfirmationSent": string;
        "accountRegistered": string;
        "isString": string;
        "loginDone": string;
        "fcmExists": string;
    };
    "common": {
        "test": string;
        "success": string;
        "greeting": string;
        "operationCompleted": string;
    };
    "errors": {
        "facilityNotFound": string;
        "facilityInactive": string;
        "UserNotAuthenticated": string;
        "NotFound": string;
        "OwnerNotAuthorized": string;
        "InternalServerError": string;
        "phoneNotFound": string;
        "UserNotAuthorized": string;
    };
    "payment": {
        "stripeError": string;
        "unexpectedError": string;
        "paymentCompleted": string;
        "paymentNotHandled": string;
        "paymentNotFound": string;
        "paymentNotCompleted": string;
        "capacityExceeded": string;
        "MayCapacityExceeded": string;
        "alreadyProcessed": string;
        "alreadyDeclined": string;
    };
    "reservations": {
        "requiredDate": string;
        "invalidDateFormat": string;
        "dateMustBeFuture": string;
        "slotNotFound": string;
        "availabilityNotFound": string;
        "facilityNotFound": string;
        "slotMismatch": string;
        "alreadyReserved": string;
        "reservationCreated": string;
        "slotBlocked": string;
        "reservationCreatedPending": string;
        "invalidPaymentMethodId": string;
        "paymentMethodIdRequired": string;
        "invalidAmount": string;
        "amountRequired": string;
        "reservationNotFound": string;
    };
    "schedules": {
        "invalidDayOfWeek": string;
        "invalidTimeFormat": string;
        "startMustBeBeforeEnd": string;
        "invalidIntervalFormat": string;
        "duplicateDay": string;
        "start_before_end": string;
        "invalidIntervalRange": string;
        "dateMustBeFuture": string;
    };
    "users": {
        "statusRequired": string;
        "invalidStatus": string;
        "currentPasswordRequired": string;
        "newPasswordRequired": string;
        "passwordConfirmationRequired": string;
        "passwordMinLength": string;
        "passwordsDoNotMatch": string;
        "emailAlreadyInUse": string;
        "phoneAlreadyInUse": string;
        "firstNameRequired": string;
        "firstNameMinLength": string;
        "firstNameMaxLength": string;
        "lastNameRequired": string;
        "lastNameMinLength": string;
        "lastNameMaxLength": string;
        "invalidEmail": string;
        "emailMaxLength": string;
        "invalidPhoneNumber": string;
        "invalidLatitude": string;
        "invalidLongitude": string;
        "deleteUser": string;
        "deleteOwner": string;
        "errors": {
            "user_not_found": string;
            "wrong_password": string;
            "owner_not_found": string;
            "invalid_status": string;
            "owner_not_found_by_user": string;
            "unauthorized": string;
            "token_not_found": string;
        };
        "success": {
            "password_updated": string;
            "profile_updated": string;
            "profile_deleted": string;
            "logged_out": string;
            "status_changed": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
